
services:
  client:
    build: 
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - path: .
          action: sync
          ignore:
            - package-lock.json
            - yarn.lock
          target: /app
        - path: ./package.json
          action: rebuild
          target: /app/package.json
