version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - URL=${URL}
    restart: unless-stopped
    container_name: game_blog
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./public/content:/app/public/content
